export  interface stagiaire{
    idStagiaire:number,
    Compte_idCompte:number,
    Encadrant_idEncadrant:number,
    Stage_idStage:number,
    nomStagiaire:string,
    prenomStagiaire:string,
    piece_identite:string,
    num_piece_identite:string,
    genre:string,
    nationalite:string,
    gouvernorat:string,
    mobile:number,
    diplome:string,
    specialite:string,
    institut:string,
    indemnite:number,
 }